### ISSUE TITLE
Add translation in the option page

### ISSUE THREAD

**Issue by patou** [Muffo/fullyfeedly#24]
Add translation of the option page.

An article who help to add the transaction on it : 
http://tumble.jeremyhubert.com/post/7076881720/translating-html-in-a-chrome-extension

**Comment by patou** [comment]
And for button text

**Comment by Muffo** [comment]
The article is very useful!

Integrating these changes to the option page should not be difficult.

**Comment by patou** [comment]
I work on it.

**Comment by Muffo** [comment]
Thanks a lot!! This is really great 👍 

I'll review the changes and leave some feedback.
My plan would be to create a new release of the extension as soon as this is merged.

**Comment by Muffo** [comment]
Pull request #25 has been merged.
Closing the issue
