### ISSUE TITLE
Change language of Feedly

### ISSUE THREAD

**Issue by Muffo** [Muffo/fullyfeedly#28]
Pull request #25 added the translation of the buttons "Show full article" and "Show article preview".

I was adding the Italian version and then I realized that my Feedly is all in English:

<img width="695" alt="schermata 2016-09-24 alle 12 56 34" src="https://cloud.githubusercontent.com/assets/538925/18808323/9fcaffb6-8256-11e6-8ff3-ec0595293985.png">

Is it just a configuration of my account? Or there isn't actually a localized version of Feedly?
In the second case, I am not really sure that translating just the button would make a lot of sense.

What do you think @patou ?

**Comment by patou** [comment]
Yes you are right, there are no translation in feedly.
We allways read all in English and French, we don't have attention of this.
