### ISSUE TITLE
End of Readability API

### ISSUE THREAD

**Issue by patou** [Muffo/fullyfeedly#37]
http://us11.campaign-archive1.com/?u=e292215ae3908888b1cdb6204&id=22954315f4&e=2be60e9f1e

**Comment by Muffo** [comment]
Thanks for bringing this up!

We have already introduced the support for the Mercury API and a banner informs the user of the migration.
I am planning to remove all the code related to Readability from the extension after the 10th of December.

**Comment by patou** [comment]
Yes Thanks, I see it after.
