### ISSUE TITLE
Replace Mercury Web Parser API

### ISSUE THREAD

**Issue by Muffo** [Muffo/fullyfeedly#46]
The Mercury Web Parser API will be shut down and stop responding to requests on April 15, 2019.

The Mercury Parser code is now free and open-source, as well as the code that powered the [Mercury Parser API](https://github.com/postlight/mercury-parser-api). I'll see if it is possible to deploy this in a AWS instance.

**Comment by Muffo** [comment]
Pull request #47 replaces the Mercury parser with a new instance deployed on AWS.

I am planning to release a new version on the Chrome web store in about 1 week/10 days. Before that, can anyone give it a try to make sure everything works as expected?

@churchs19 , the Firefox extension will need to be updated as well.

**Comment by churchs19** [comment]
I'll take a look at this for sure. I was looking into actually pulling the updated API library into the extension itself, but this works too. :+1: Have you looked into or estimated the cost for running this in AWS?

**Comment by Muffo** [comment]
Good question! It's quite difficult to make an estimate now because I am not sure how many people are actually using the extension and how many pages they request every day.

The [pricing of AWS Lambda](https://aws.amazon.com/lambda/pricing/) is based on:
* Number of function calls
* Duration of the requests (with increments of 100ms) and memory usage

After we roll-out the updated extension I'll have access to all the statistics. That should give us a better idea of the cost and we'll see if the free tier (which includes 1M requests + 400,000 GB-seconds) is enough.

> I was looking into actually pulling the updated API library into the extension itself

This would be interesting to try, although the extension would need access to all the URLs and it might scare people away.

**Comment by churchs19** [comment]
I updated and published the Firefox version with the updated URL today.

**Comment by saputnik** [comment]
> I am planning to release a new version on the Chrome web store in about 1 week/10 days. Before that, can anyone give it a try to make sure everything works as expected?

I have version 0.10.0 and the extensions seems not be working anymore

**Comment by Muffo** [comment]
I'll try to update the extension as soon as possible. Out of curiosity, what kind of error are you getting?

The official Mercury API should keep working until April 15th.

**Comment by saputnik** [comment]
> I'll try to update the extension as soon as possible. Out of curiosity, what kind of error are you getting?
> 
> The official Mercury API should keep working until April 15th.

Hey, thank you so much! I get the 'loading' message and nothing else happens. I have also to fully refresh feedly to get it away

**Comment by churchs19** [comment]
I've also seen the issue @saputnik is mentioning here. I believe it is a timeout by the existing Postlight-hosted Mercury API. I can confirm that I haven't seen it yet with the new version of the API.
